# Generated by Django 6.0.1 on 2026-01-23 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Тип области')),
                ('size', models.PositiveIntegerField(verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Область эффекта',
                'verbose_name_plural': 'Области эффекта',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('world_story', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Кампания',
                'verbose_name_plural': 'Кампании',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название класса')),
                ('hit_die', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кость хитов')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='DamageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа урона')),
            ],
            options={
                'verbose_name': 'Тип урона',
                'verbose_name_plural': 'Типы урона',
            },
        ),
        migrations.CreateModel(
            name='MagicSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название школы')),
                ('desc', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Школа магии',
                'verbose_name_plural': 'Школы магии',
            },
        ),
        migrations.CreateModel(
            name='CharacterSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('race', models.CharField(max_length=50)),
                ('background', models.CharField(blank=True, max_length=50)),
                ('strength', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('constitution', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('wisdom', models.IntegerField(default=10)),
                ('charisma', models.IntegerField(default=10)),
                ('max_hit_points', models.IntegerField(default=10)),
                ('current_hit_points', models.IntegerField(default=10)),
                ('armor_class', models.IntegerField(default=10)),
                ('speed', models.IntegerField(default=30)),
                ('inspiration', models.BooleanField(default=False)),
                ('skills', models.TextField(blank=True)),
                ('equipment', models.TextField(blank=True)),
                ('spells', models.TextField(blank=True)),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='accounts.class')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='accounts.charactersheet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('description', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.campaign')),
            ],
            options={
                'verbose_name': 'Сессия',
                'verbose_name_plural': 'Сессии',
            },
        ),
        migrations.CreateModel(
            name='DMNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_notes', to='accounts.session')),
            ],
            options={
                'verbose_name': 'Записка мастера',
                'verbose_name_plural': 'Записи мастера',
            },
        ),
        migrations.CreateModel(
            name='SpellDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_at_slot_level', models.JSONField(blank=True, help_text='Словарь, где ключ - уровень слота заклинания, значение - формула урона. Например: {"1": "2d6", "2": "3d6"}', null=True, verbose_name='Урон по уровням слотов')),
                ('damage_at_character_level', models.JSONField(blank=True, help_text='Словарь, где ключ - уровень персонажа, значение - формула урона. Например: {"5": "3d8", "10": "4d8"}', null=True, verbose_name='Урон по уровням персонажа')),
                ('damage_type', models.ForeignKey(blank=True, help_text='Тип урона, который наносит заклинание (огонь, холод, яд и т.д.)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.damagetype', verbose_name='Тип урона')),
            ],
            options={
                'verbose_name': 'Урон заклинания',
                'verbose_name_plural': 'Уроны заклинаний',
            },
        ),
        migrations.CreateModel(
            name='SpellDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_type', models.CharField(help_text='Характеристика, используемая для спасброска против заклинания', max_length=50, verbose_name='Тип спасброска')),
                ('dc_success', models.CharField(choices=[('half', 'Половина урона'), ('none', 'Нет эффекта'), ('full', 'Полный эффект'), ('quarter', 'Четверть урона')], help_text='Что происходит при успешном спасброске: половина урона, нет эффекта и т.д.', max_length=20, verbose_name='Результат успешного спасброска')),
                ('desc', models.TextField(blank=True, help_text='Дополнительные детали о спасброске против этого заклинания', null=True, verbose_name='Дополнительное описание')),
            ],
            options={
                'verbose_name': 'Спасбросок заклинания',
                'verbose_name_plural': 'Спасброски заклинаний',
                'indexes': [models.Index(fields=['dc_success'], name='accounts_sp_dc_succ_a1a3ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название подкласса')),
                ('parent_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subclasses', to='accounts.class', verbose_name='Родительский класс')),
            ],
            options={
                'verbose_name': 'Подкласс',
                'verbose_name_plural': 'Подклассы',
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полное название заклинания', max_length=255, verbose_name='Название')),
                ('index', models.SlugField(help_text='Уникальный идентификатор заклинания', unique=True, verbose_name='Индекс')),
                ('level', models.PositiveSmallIntegerField(help_text='Уровень заклинания (0 для заклинаний нулевого круга/заговоров)', verbose_name='Уровень')),
                ('casting_time', models.CharField(help_text='Сколько времени требуется для накладывания заклинания (1 действие, 1 минута, 8 часов и т.д.)', max_length=100, verbose_name='Время накладывания')),
                ('duration', models.CharField(help_text='Как долго действует заклинание (мгновенно, 1 минута, до рассеивания и т.д.)', max_length=100, verbose_name='Длительность')),
                ('range', models.CharField(help_text='На каком расстоянии можно наложить заклинание (дотягиваемся, 30 футов, 1 миля и т.д.)', max_length=100, verbose_name='Дистанция')),
                ('components', models.JSONField(default=list, help_text='Необходимые компоненты для накладывания: V (вербальный), S (соматический), M (материальный)', verbose_name='Компоненты')),
                ('ritual', models.BooleanField(default=False, help_text='Можно ли наложить это заклинание как ритуал (без расхода слота заклинания)', verbose_name='Ритуал')),
                ('concentration', models.BooleanField(default=False, help_text='Требует ли заклинание концентрации для поддержания эффекта', verbose_name='Концентрация')),
                ('desc', models.JSONField(default=list, help_text='Основное описание эффектов заклинания, каждая строка - отдельный абзац', verbose_name='Описание')),
                ('higher_level', models.JSONField(blank=True, default=list, help_text='Дополнительные эффекты или усиления при наложении заклинания с использованием слотов более высокого уровня', verbose_name='Эффекты на более высоких уровнях')),
                ('material', models.TextField(blank=True, help_text='Описание специфических материальных компонентов, если они требуются и имеют особую ценность или свойства', null=True, verbose_name='Материальные компоненты')),
                ('attack_type', models.CharField(blank=True, help_text='Тип атаки, если заклинание требует броска атаки (ближняя, дальнобойная и т.д.)', max_length=50, null=True, verbose_name='Тип атаки')),
                ('heal_at_slot_level', models.JSONField(blank=True, help_text='Словарь, где ключ - уровень слота заклинания, значение - формула исцеления. Например: {"1": "2d4", "2": "3d4"}', null=True, verbose_name='Исцеление по уровням слотов')),
                ('area_of_effect', models.ForeignKey(blank=True, help_text='Детали области, на которую распространяется действие заклинания (конус, сфера, куб и т.д.)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.areaofeffect', verbose_name='Область эффекта')),
                ('classes', models.ManyToManyField(blank=True, help_text='Классы персонажей, которые могут изучать и использовать это заклинание', related_name='spells', to='accounts.class', verbose_name='Классы')),
                ('school', models.ForeignKey(help_text='Школа магии, к которой принадлежит заклинание (очарование, иллюзия, разрушение и т.д.)', on_delete=django.db.models.deletion.CASCADE, to='accounts.magicschool', verbose_name='Школа магии')),
                ('damage', models.OneToOneField(blank=True, help_text='Детали урона, наносимого заклинанием, включая тип урона и формулы по уровням', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.spelldamage', verbose_name='Урон')),
                ('dc', models.OneToOneField(blank=True, help_text='Детали спасброска, который должны совершать цели для сопротивления эффектам заклинания', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.spelldc', verbose_name='Спасбросок')),
                ('subclasses', models.ManyToManyField(blank=True, help_text='Подклассы, которые получают доступ к этому заклинанию (если применимо)', related_name='spells', to='accounts.subclass', verbose_name='Подклассы')),
            ],
            options={
                'verbose_name': 'Заклинание',
                'verbose_name_plural': 'Заклинания',
                'db_table': 'dnd_spells',
                'ordering': ['name', 'level'],
                'indexes': [models.Index(fields=['name'], name='dnd_spells_name_0a8ebd_idx'), models.Index(fields=['level'], name='dnd_spells_level_5815a7_idx'), models.Index(fields=['index'], name='dnd_spells_index_5907b6_idx'), models.Index(fields=['casting_time'], name='dnd_spells_casting_1e6652_idx'), models.Index(fields=['duration'], name='dnd_spells_duratio_723b85_idx'), models.Index(fields=['range'], name='dnd_spells_range_8a7ed3_idx'), models.Index(fields=['ritual'], name='dnd_spells_ritual_dc9ce7_idx')],
            },
        ),
    ]
