# Generated by Django 6.0.1 on 2026-01-30 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='accounts.charactersheet'),
        ),
        migrations.CreateModel(
            name='CampaignNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='accounts.campaign')),
            ],
            options={
                'verbose_name': 'Заметка кампании',
                'verbose_name_plural': 'Заметки кампании',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='accounts.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чата',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Storyline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storylines', to='accounts.campaign')),
            ],
            options={
                'verbose_name': 'Линия сюжета',
                'verbose_name_plural': 'Линии сюжета',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StoryOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('condition', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('storyline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='accounts.storyline')),
            ],
            options={
                'verbose_name': 'Исход события',
                'verbose_name_plural': 'Исходы событий',
                'ordering': ['order', 'id'],
            },
        ),
    ]
