# Generated by Django 6.0.1 on 2026-02-05 00:00

import secrets
import string

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _generate_join_code():
    alphabet = string.ascii_uppercase + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(8))


def assign_owner_and_codes(apps, schema_editor):
    Campaign = apps.get_model("accounts", "Campaign")
    CharacterSheet = apps.get_model("accounts", "CharacterSheet")
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)

    existing = set(
        Campaign.objects.exclude(join_code__isnull=True)
        .exclude(join_code="")
        .values_list("join_code", flat=True)
    )
    for campaign in Campaign.objects.filter(models.Q(join_code__isnull=True) | models.Q(join_code="")):
        code = _generate_join_code()
        while code in existing:
            code = _generate_join_code()
        existing.add(code)
        campaign.join_code = code
        campaign.save(update_fields=["join_code"])

    first_user = User.objects.first()
    if first_user:
        Campaign.objects.filter(owner__isnull=True).update(owner=first_user)
        CharacterSheet.objects.filter(owner__isnull=True).update(owner=first_user)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_campaign_characters_campaignnote_chatmessage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_sheets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="max_players",
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name="campaign",
            name="join_code",
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="campaign",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="CampaignJoinRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Ожидает"), ("accepted", "Принят"), ("rejected", "Отклонён")],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="accounts.campaign",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_join_requests",
                        to="accounts.charactersheet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_join_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на вступление",
                "verbose_name_plural": "Заявки на вступление",
            },
        ),
        migrations.RunPython(assign_owner_and_codes, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="campaignjoinrequest",
            unique_together={("campaign", "user")},
        ),
        migrations.AddIndex(
            model_name="campaignjoinrequest",
            index=models.Index(fields=["status"], name="accounts_ca_status_47a10a_idx"),
        ),
        migrations.AddIndex(
            model_name="campaignjoinrequest",
            index=models.Index(fields=["campaign", "status"], name="accounts_ca_campaign_5f92db_idx"),
        ),
        migrations.AddIndex(
            model_name="campaignjoinrequest",
            index=models.Index(fields=["user", "status"], name="accounts_ca_user_id_8e3b7f_idx"),
        ),
    ]
