# Generated by Django 6.0.2 on 2026-02-06 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_character_sheet_layout'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='campaignjoinrequest',
            new_name='accounts_ca_status_3d881d_idx',
            old_name='accounts_ca_status_47a10a_idx',
        ),
        migrations.RenameIndex(
            model_name='campaignjoinrequest',
            new_name='accounts_ca_campaig_923877_idx',
            old_name='accounts_ca_campaign_5f92db_idx',
        ),
        migrations.RenameIndex(
            model_name='campaignjoinrequest',
            new_name='accounts_ca_user_id_729e1e_idx',
            old_name='accounts_ca_user_id_8e3b7f_idx',
        ),
    ]
